### ISSUE TITLE
Help! All my recipes are borked by zipped tiffs

### ISSUE THREAD

**Issue by thodson-usgs** [hytest-feedstocks/ssebop-feedstock#2]
Zipped tiffs are the bane of my existence lately. I guess this was a popular legacy format, such that most of my inquiries at USGS  

I've hacked through several attempts (below). Some run locally, some run locally but are buggy, and none run on Flink.
Some recipes include zip sugar in the file pattern, some open the url with `fsspec`, some pass the url to `xarray`. 
```
# example zip sugar
input_url_pattern = (
    'zip+'  # zip sugar
    'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/'
    'conus/eta/modis_eta/daily/downloads/'
    'det{yyyyjjj}.modisSSEBopETactual.zip'
    '!/det{yyyyjjj}.modisSSEBopETactual.tif' # zip sugar
)
```

## branch [main](https://github.com/hytest-feedstocks/ssebop-feedstock/blob/master/feedstock/recipe.py)
- skip `OpenWithFSSpec`  and `OpenWithXarray`. Pass zip sugar url directly to preprocessing step
```
da = rioxarray.open_rasterio(url)
```
- direct runner: runs but doesn't cache input files
- flink: Fails
```
Caused by: java.lang.RuntimeException: Error received from SDK harness for instruction 2: Traceback (most recent call last):
  File "/opt/apache/beam-venv/beam-venv-worker-2-1/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/opt/apache/beam-venv/beam-venv-worker-2-1/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<function open at 0x7f90bf608310>, ('zip+https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip!/det2000001.modisSSEBopETactual.tif',), 'r', (('sharing', False),), '39cb8b8a-fa8a-43b4-8b95-e4c37ddad095']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rasterio/_base.pyx", line 310, in rasterio._base.DatasetBase.__init__
  File "rasterio/_base.pyx", line 221, in rasterio._base.open_dataset
  File "rasterio/_err.pyx", line 221, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: '/vsizip/vsicurl/https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip/det2000001.modisSSEBopETactual.tif' does not exist in the file system, and is not recognized as a supported dataset name.
```

## branch [fsspec_v2](https://github.com/hytest-feedstocks/ssebop-feedstock/blob/fsspec_v2/feedstock/recipe.py)
- skip `OpenWithFSSpec` and open the zip sugar url directly with
```
    | OpenURLWithFSSpec(open_kwargs={'compression': 'zip'})
```
- direct runner: runs but doesn't cache input files
- flink: Fails
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error received from SDK harness for instruction 1: Traceback (most recent call last):
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
KeyError: [<function open at 0x7f0f84e10700>, ('zip+https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip!/det2000001.modisSSEBopETactual.tif',), 'r', (('sharing', False),), '67a5169c-be67-485b-af0e-1a269c8160ad']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rasterio/_base.pyx", line 310, in rasterio._base.DatasetBase.__init__
  File "rasterio/_base.pyx", line 221, in rasterio._base.open_dataset
  File "rasterio/_err.pyx", line 221, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: '/vsizip/vsicurl/https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip/det2000001.modisSSEBopETactual.tif' does not exist in the file system, and is not recognized as a supported dataset name.
```

## branch [fsspec_v3](https://github.com/hytest-feedstocks/ssebop-feedstock/blob/fsspec_v3/feedstock/recipe.py)
-  I think this is the cleanest version. No zip sugar in the url, then
```
    | OpenURLWithFSSpec(open_kwargs={'compression': 'zip'})
    | OpenWithXarray(xarray_open_kwargs={'engine': 'rasterio'})
```
- direct runner: runs but caches unzipped tiff with `.zip` extension, fails on second run with 
```
AttributeError: 'ZipExtFile' object has no attribute 'size' [while running 'Create|OpenURLWithFSSpec|OpenWithXarray|Preprocess|StoreToZarr/OpenURLWithFSSpec/MapWithConcurrencyLimit/open_url']
```
- flink: Fails
```
(MapPartition at [1]Create|OpenURLWithFSSpec|OpenWithXarray|Preprocess|StoreToZarr/Create/FlatMap(<lambda at core.py:3774>)) -> FlatMap (FlatMap at ExtractOutput[0]) (1/1)#0 73ddb4ce122ddd9b56031492db1c7122_38f1cb4b30fd748754aacbac4d191f6a_0_0.
2024-02-01 23:03:37,819 INFO  /opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py:179 [] - Caching file 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip'
2024-02-01 23:03:38,030 INFO  /opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py:190 [] - Copying remote file 'https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip' to cache
```
... and fiinally
```
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/pangeo_forge_recipes/openers.py", line 32, in open_url
    cache.cache_file(url, secrets, **kw)
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py", line 191, in cache_file
    _copy_btw_filesystems(input_opener, target_opener)
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/pangeo_forge_recipes/storage.py", line 32, in _copy_btw_filesystems
    with input_opener as source:
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/fsspec/core.py", line 103, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/fsspec/spec.py", line 1295, in open
    f = self._open(
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/fsspec/implementations/http.py", line 359, in _open
    size = size or self.info(path, **kwargs)["size"]
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/opt/apache/beam-venv/beam-venv-worker-1-1/lib/python3.10/site-packages/fsspec/implementations/http.py", line 433, in _info
    raise FileNotFoundError(url) from exc
FileNotFoundError: https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip [while running 'Create|OpenURLWithFSSpec|OpenWithXarray|Preprocess|StoreToZarr/OpenURLWithFSSpec/MapWithConcurrencyLimit/open_url']
```

## branch [fsspec_v4](https://github.com/hytest-feedstocks/ssebop-feedstock/blob/fsspec_v4/feedstock/recipe.py)
- The most hacky attempt: unzip the tiffs manually, cache them, then pass the filename of the cached file to `OpenWithXarray`
- direct runner: runs and caches the data
- flink: fails, not sure why, but the tasks seem to hang, probably looking for the cached data

**Comment by thodson-usgs** [comment]
@cisaacstern, @moradology.
I wrote up some notes about my struggle with zipped tiff recipes. Maybe you have advice on a way forward?
This and AWS have always been the main barriers to adoption at USGS. One down, one to go.

**Comment by moradology** [comment]
I've not looked deeply into this yet but this translation looks a bit funny: `/vsizip/vsicurl/https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip/det2000001.modisSSEBopETactual.tif`

I think this is the correct format: `/vsizip//vsicurl/https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip/det2000001.modisSSEBopETactual.tif`

EDIT: I was right but gdal is apparently permissive.
```
gdalinfo /vsizip/vsicurl/https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/uswem/web/conus/eta/modis_eta/daily/downloads/det2000001.modisSSEBopETactual.zip/det2000001.modisSSEBopETactual.tif
Driver: GTiff/GeoTIFF
etc. etc. etc.
```

Do we by chance know the versions of gdal/rasterio being used, @thodson-usgs? this may be useful, as I'm seeing that there have been some vsi filesystem bugs in rasterio
```python
import rasterio
rasterio.show_versions()
```

**Comment by thodson-usgs** [comment]
Good thought.
I'm not sure exactly sure how to do that through Flink, but installing `requirements.txt` in a clean local environment yields
```
  rasterio: 1.3.9
      GDAL: 3.6.4
      PROJ: 9.0.1
      GEOS: 3.11.1
 PROJ DATA: /home/thodson/miniforge3/envs/recipe-debug/lib/python3.10/site-packages/rasterio/proj_data
 GDAL DATA: /home/thodson/miniforge3/envs/recipe-debug/lib/python3.10/site-packages/rasterio/gdal_data

System:
    python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
executable: /home/thodson/miniforge3/envs/recipe-debug/bin/python
   machine: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

Python deps:
    affine: 2.4.0
     attrs: 23.2.0
   certifi: 2023.11.17
     click: 8.1.7
     cligj: 0.7.2
    cython: None
     numpy: 1.24.4
    snuggs: 1.4.7
click-plugins: None
setuptools: 69.0.3
```
...pretty close to what I'm using with DirectRunner (where the recipe works)
```
  rasterio: 1.3.9
      GDAL: 3.6.4
      PROJ: 9.0.1
      GEOS: 3.11.1
 PROJ DATA: /home/thodson/miniforge3/envs/pangeo-forge-dev/lib/python3.10/site-packages/rasterio/proj_data
 GDAL DATA: /home/thodson/miniforge3/envs/pangeo-forge-dev/lib/python3.10/site-packages/rasterio/gdal_data

System:
    python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
executable: /home/thodson/miniforge3/envs/pangeo-forge-dev/bin/python
   machine: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

Python deps:
    affine: 2.4.0
     attrs: 23.2.0
   certifi: 2023.11.17
     click: 8.1.7
     cligj: 0.7.2
    cython: 3.0.8
     numpy: 1.26.3
    snuggs: 1.4.7
click-plugins: None
setuptools: 69.0.3
```

**Comment by moradology** [comment]
So, in addition to GDAL apparently handling things as expected rio 1.4 seems to be capable:
![image](https://github.com/hytest-feedstocks/ssebop-feedstock/assets/1977405/2302d7f9-03b6-4628-b2ce-566a536904d7)

**Comment by thodson-usgs** [comment]
I believe this is sorted now. 
The gist of the pattern is shown in the Preprocess transform in https://github.com/hytest-feedstocks/ssebop-feedstock/blob/master/feedstock/recipe.py

The solution is a little gnarly but it should generalize for all the other weird zipping conventions we're coming across.
